<?php

namespace Cbnv\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
	/**
	* Get entity field names
	*
	* @return array 
	*/
    public static function getFields() {
        return array(
            'title'         => 'Titre',
            'description'   => 'Description'
        );
    }
}
