<?php

namespace Cbnv\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
  	/**
	* Get entity field names
	*
	* @return array 
	*/
    public static function getFields() {
        return array(
            'title' => 'Titre',
            'content' => 'Contenu',
            'date' => 'Date'
        );
    }
}
