<?php

namespace Cbnv\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
  	/**
	* Get entity field names
	*
	* @return array 
	*/
    public static function getFields() {
        return array(
            'title'     => 'Titre',
            'catchline' => 'Accroche',
            'date'      => 'Date'
        );
    }

    public function getPaginator($page = 1, $nbrByPage = 5) {
        $query = $this->_em->createQueryBuilder('a')
            ->select('a')
            ->from('CbnvMainBundle:Article', 'a')
            ->orderBy('a.date', 'ASC')
            ->getQuery();
        $query->setFirstResult(($page-1) * $nbrByPage)
            ->setMaxResults($nbrByPage);

        return new Paginator($query);
    }
}
