<?php

namespace Cbnv\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
	/**
	* Get entity field names
	*
	* @return array 
	*/
    public static function getFields() {
        return array(
            'firstName' => 'Prénom',
            'lastName'  => 'Nom',
            'email'     => 'Email'
        );
    }
}
