<?php

namespace Cbnv\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
	/**
	* Get entity field names
	*
	* @return array 
	*/
    public static function getFields() {
        return array(
            'alt' => 'Nom',
            'date' => 'Date'
        );
    }
}
