parameters:
#    cbnv_main.example.class: Cbnv\MainBundle\Example

services:
#    cbnv_main.example:
#        class: %cbnv_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
